version: '3'

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"

    depends_on:
      - frontend

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"