# version: '3'

# services:
#   db:
#     container_name: mysql
#     image: mysql:latest
#     ports:
#       - "3307:3307"
#     environment:
#       # MYSQL_ROOT_PASSWORD: root
#       # MYSQL_DATABASE: matcch
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: matcch
#       # MYSQL_USER: user1
#       # MYSQL_PASSWORD: u1

#   # migrate:
#   #   build: ./Backend
#   #   depends_on:
#   #     - db
#   #   environment:
#   #     FLASK_APP: app.py
#   #   command: >
#   #     bash -c "flask db init" 
#   #     bash -c "flask db migrate" 
#   #     bash -c "flask db upgrade"

#   flask-app:
#     build: ./Backend
#     depends_on:
#       - db
#     ports:
#       - "5000:5000"
#     environment:
#       FLASK_APP: app.py
#       MYSQL_HOST: db
#       MYSQL_USER: root
#       MYSQL_PASSWORD : root
#       MYSQL_DATABASE: matcch
#     # command: flask run --host=0.0.0.0


# version: '3'

# services:
#   db:
#     container_name: db
#     image: postgres:12
#     ports:
#       - "3307:3307"
#     environment:
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=postgres



#   flask-app:
#     build: ./Backend
#     depends_on:
#       - db
#     ports:
#       - "5000:5000"
#     links:
#       - db

    # command: flask run --host=0.0.0.0



# version: '3'

# services:
#   # db:
#   #   container_name: mysql
#   #   image: mysql:latest
#   #   ports:
#   #     - "3307:3307"
#   #   environment:
#   #     MYSQL_ROOT_PASSWORD: root
#   #     MYSQL_DATABASE: matcch

#   flask-app:
#     build: ./Backend
#     # depends_on:
#     #   - db
#     ports:
#       - "5000:5000"
#     command: flask run --host=0.0.0.0


version: '3'

services:
  db:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: matcch
    networks:
      - my-network

  flask-app:
    build: ./Backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: matcch
    networks:
      - my-network

networks:
  my-network:
