
# version: '3'

# services:
#   database:
#     container_name: mysql-container
#     image: mysql:latest
#     restart: always
#     ports:
#       - "3307:3306"
#     expose:
#       - '3307'
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: matcch
#       MYSQL_USER: intern
#     # networks:
#     #   - my-network

#   # flask-app:
#   #   build: ./Backend
#   #   depends_on:
#   #     - database
#   #   ports:
#   #     - "5000:5000"
#   #   environment:
#   #     FLASK_APP: app.py
#   #     MYSQL_HOST: database
#   #     MYSQL_USER: root
#   #     MYSQL_PASSWORD: root
#   #     MYSQL_DATABASE: matcch
#   #   networks:
#   #     - my-network

# # networks:
# #   my-network:


# version: "3.7"
# services:
#   mysql:
#     image: mysql:latest
#     container_name: mysql-container
#     restart: always                       # always restart
#     environment:
#       MYSQL_DATABASE: 'test'              # name of database
#       MYSQL_USER: 'sample'                # sample is the name of user
#       MYSQL_PASSWORD: 'password'          # password for sample user
#       MYSQL_ROOT_PASSWORD: 'password'     # password for root user
#     ports:
#       - '4000:3306'                       # host port 3306 is mapper to docker port 3306
#     expose:
#       - '3306'
#     volumes:
#       - mysql-db:/var/lib/mysql
# volumes:
#         mysql-db:


version: '3'

services:
  app:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=mysql+pymysql://username:password@db:3306/dbname
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dbname
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: