"""empty message

Revision ID: c06806de584b
Revises: 
Create Date: 2024-04-12 15:58:20.358193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06806de584b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('Open', sa.Integer(), nullable=False),
    sa.Column('Consc', sa.Integer(), nullable=False),
    sa.Column('Extrav', sa.Integer(), nullable=False),
    sa.Column('Agree', sa.Integer(), nullable=False),
    sa.Column('Neuro', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_score')
    op.drop_table('users')
    # ### end Alembic commands ###
