"""empty message

Revision ID: 7fa4606bbd23
Revises: 
Create Date: 2024-04-02 12:25:40.817335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa4606bbd23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_score',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('Open', sa.Integer(), nullable=False),
    sa.Column('Consc', sa.Integer(), nullable=False),
    sa.Column('Extrav', sa.Integer(), nullable=False),
    sa.Column('Agree', sa.Integer(), nullable=False),
    sa.Column('Neuro', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=250), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('mobile')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_score')
    # ### end Alembic commands ###
